name: Master
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: dev
    - name: Set up python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        make install
    - name: Linting
      run: |
        make lint
    - name: Testing scrips
      run: |
        make test
    - name: Formatting .py files
      run: |
        make format
    - name: Running
      run: |
        echo "Running!"
        python pushing_data.py
        echo "Done"
